name: challenge
description: A motivational application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #NEW
  flutter_i18n: ^0.8.3  
  auto_route: ^0.2.2
  states_rebuilder: ^1.11.2
  json_serializable: ^3.2.5
  flutter_dotenv: ^2.1.0
  equatable: ^1.0.1
  dio: ^2.1.16
  injectable: ^0.2.3
  get_it: ^4.0.0
  flutter_hooks: ^0.7.0
  dartz: ^0.8.9
  flare_flutter: ^2.0.1
  #ENDNEW
  intro_views_flutter: ^2.6.0
  shared_preferences: ^0.5.1+1
  url_launcher: ^5.0.2
  fluttertoast: ^3.0.4
  bloc:  ^0.15.0
  flutter_bloc: ^0.21.0
  flutter_custom_clippers: ^0.1.1
  cached_network_image: 2.0.0-rc.1
  contacts_service: ^0.2.8
  permission_handler: ^3.1.0
  share: ^0.6.1+1
  flushbar: '1.8.0'
  built_value: ^7.0.8
  flutter:
    sdk: flutter
    

dev_dependencies:
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8
  injectable_generator: ^0.2.3
  lint: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - .env
    - lang/


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700