name: challenge
description: A motivational application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependency_overrides: 
  intl: ^0.17.0-nullsafety.2

dependencies:
  flutter_i18n: ^0.19.0
  auto_route: ^0.6.7
  states_rebuilder: ^2.3.1
  equatable: ^1.2.3
  dio: ^3.0.10
  injectable: ^1.0.4
  get_it: ^4.0.4
  flutter_hooks: ^0.13.1
  dartz: ^0.9.1
  flare_flutter: ^2.0.6
  intro_views_flutter: ^2.8.1
  shared_preferences: ^0.5.8
  fluttertoast: ^7.0.2
  flutter_custom_clippers: ^1.1.1
  cached_network_image: 2.2.0+1
  challange_shared:
    path: ../shared/
  flutter:
    sdk: flutter
  division: ^0.8.8
  freezed_annotation: ^0.11.0+1
  functional_widget_annotation: ^0.8.0

dev_dependencies:
  functional_widget: ^0.8.0
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4
  lint: ^1.2.0
  freezed: ^0.11.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/icons/
    - assets/fixtures/
    - lang/

  fonts:
    - family: raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: raleway-bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
